### ISSUE TITLE
Installing gcp-storage-emulator==2022.4.9 breaks tests

### ISSUE THREAD

**Issue by jakubczaplicki** [oittaa/gcp-storage-emulator#163]
**Describe the bug**
Having a repo with tests under `tests` folder, installation of gcp-storage-emulator causes pytest to detect :  
`/venv/lib/python3.9/site-packages/tests/__init__.py` instead.

**To Reproduce**
Prepare a small repo with a folder `tests`, in which a file imports something from `tests` module (e.g. fixtures).
Run pytest before installation of the `gcp-storage-emulator` and after.

**Expected behavior**
The tests of any system should work as before the installation.

**System (please complete the following information):**
- OS version: MacOS
- Python version: 3.9.12
- gcp-storage-emulator version: 2022.4.9

**Additional context**
I suspect the `tests` is being recognised as a module for installation and is being installed as such.

**Comment by oittaa** [comment]
> I suspect the tests is being recognised as a module for installation and is being installed as such.

Oh yeah, you're right.  https://github.com/oittaa/gcp-storage-emulator/pull/164 should fix the issue. I moved the package under `src` which seems to be the modern recommendation and now `find_packaged()` in `setup.py` should only detect the files inside that directory. 

There's a new release 2022.4.13 which includes the change.

Thanks for reporting the issue!
