### ISSUE TITLE
Module 'crc32c' has no attribute 'crc32c'

### ISSUE THREAD

**Issue by Lawrencemm** [oittaa/gcp-storage-emulator#17]
As far as I can tell my crc32c dependency is correct, could this be a python compatibility issue?

`File "lib/python3.8/site-packages/gcp_storage_emulator/handlers/objects.py", line 64, in _crc32c
    val = crc32c.crc32c(content)
AttributeError: module 'crc32c' has no attribute 'crc32c'`

**Comment by oittaa** [comment]
It's tested against these versions:  https://github.com/oittaa/gcp-storage-emulator/blob/main/.github/workflows/main.yml#L23

What does it show if you run?
```
 pip3 freeze | grep crc32c
```

**Comment by Lawrencemm** [comment]
Yeah, I'm getting 2.2 for that. I'm actually using `pipenv`- `pipenv graph` also shows 2.2 for crc32c.

**Comment by oittaa** [comment]
Works for me.

```
$ pipenv install gcp-storage-emulator
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Creating a Pipfile for this project...
Installing gcp-storage-emulator...
Adding gcp-storage-emulator to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (ed64c0)!
Installing dependencies from Pipfile.lock (ed64c0)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
```


```
$ pipenv graph
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
gcp-storage-emulator==2021.3.12
  - crc32c [required: ==2.2, installed: 2.2]
  - fs [required: ==2.4.12, installed: 2.4.12]
    - appdirs [required: ~=1.4.3, installed: 1.4.4]
    - pytz [required: Any, installed: 2021.1]
    - setuptools [required: Any, installed: 41.2.0]
    - six [required: ~=1.10, installed: 1.15.0]
pipenv==2020.11.15
  - certifi [required: Any, installed: 2020.12.5]
  - pip [required: >=18.0, installed: 19.2.3]
  - setuptools [required: >=36.2.1, installed: 41.2.0]
  - virtualenv [required: Any, installed: 20.4.3]
    - appdirs [required: >=1.4.3,<2, installed: 1.4.4]
    - distlib [required: >=0.3.1,<1, installed: 0.3.1]
    - filelock [required: >=3.0.0,<4, installed: 3.0.12]
    - six [required: >=1.9.0,<2, installed: 1.15.0]
  - virtualenv-clone [required: >=0.2.5, installed: 0.5.4]
```

```
$ gcp-storage-emulator start
Starting server at localhost:9023
[SERVER] All services started
```

**Comment by oittaa** [comment]
You need to provide some kind of minimal test case. I have no idea what's in your environment or what you're trying to do.

**Comment by oittaa** [comment]
I replaced `crc32c` with Google's implementation that comes with a pure Python implementation. It might work better in weird environments or with broken compilers.

https://github.com/oittaa/gcp-storage-emulator/commit/73b1f7921b84da983af8285f280ce4d3f9704bd2

**Comment by Lawrencemm** [comment]
Thanks, I might give that a try on Monday.

Just FYI I installed the older package that you forked from and the problem disasppeared so, not sure what's going on.

**Comment by oittaa** [comment]
Yeah, I tried to submit few pull requests for couple of features I really needed, but the original project seemed to be dead.

**Comment by oittaa** [comment]
Going to close this since there's literally no information. All the tests pass in all supported Python versions.

Pull requests are welcome, if there's an actual issue.
