### ISSUE TITLE
Docker Repo no longer exists

### ISSUE THREAD

**Issue by saifjilani** [oittaa/gcp-storage-emulator#259]
**Describe the bug**

The docker repo no longer exists: https://hub.docker.com/layers/oittaa/gcp-storage-emulator/

**To Reproduce**
[A minimal, complete, and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the behavior.

`docker pull oittaa/gcp-storage-emulator` returns a `repository does not exist` 

**Expected behavior**

**System (please complete the following information):**
- OS version:
- Python version:
- gcp-storage-emulator version:

**Additional context**

**Comment by noramehesz** [comment]
It works now.
