### ISSUE TITLE
How to integrate other languages with the emulator?

### ISSUE THREAD

**Issue by ChameleonTartu** [oittaa/gcp-storage-emulator#50]
Hi,

The emulator looks awesome. It is exactly what I was looking for. Can you help me to integrate the emulator with my Java project?

I am using Kotlin, but it's very different from Java or Python.

```
class StorageBucketTestServer(projectName: String, private val bucketName: String) {

    private val credentials: Credentials = ImpersonatedCredentials
        .newBuilder()
        .setScopes(listOf())
        .build()

    private val storage: Storage = StorageOptions
        .newBuilder()
        .setCredentials(credentials)
        .setProjectId(projectName)
        .setHost("http://localhost:9023")
        .build()
        .service

    fun upload(file: File) {
      storage[bucketName]
    }
}
```

I start emulator like this: `gcp-storage-emulator start --in-memory --default-bucket=my-common-test`

**Explanation:**

`ImpersonatedCredentials` - I create credentials similar to `AnonymousCredentials` in Python.
`StorageOptions` builder is the same as storage.Client in Python
 
 The issue happens on the line `storage[bucketName]`, claiming no buckets. More precisely, it's `NullPointerException`, which is practically the same.

What would be the correct way to access the bucket?

*Note*: I based my implementation on your examples and [baeldung.com](https://www.baeldung.com/java-google-cloud-storage) article.

**Comment by oittaa** [comment]
I have not tested with Kotlin, but more or less every language should work just fine since this is just an emulator implementing the API over HTTP.

You might want to check some tutorials at https://github.com/GoogleCloudPlatform/kotlin-samples/tree/master/storage
